import type { User, Appointment, Patient, Medication, Prescription, InventoryItem } from "./types"

// Mock Users Data
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@hospital.com",
    name: "Dr. Sarah Johnson",
    role: "admin",
    avatar: "/professional-doctor.jpg",
    department: "Administration",
    phone: "+1 (555) 123-4567",
    isActive: true,
    lastLogin: new Date("2024-01-15T09:00:00Z"),
  },
  {
    id: "2",
    email: "doctor@hospital.com",
    name: "Dr. Michael Chen",
    role: "doctor",
    avatar: "/male-doctor.png",
    department: "Cardiology",
    phone: "+1 (555) 234-5678",
    specialization: "Cardiology",
    licenseNumber: "MD12345",
    isActive: true,
    lastLogin: new Date("2024-01-15T08:30:00Z"),
  },
  {
    id: "3",
    email: "nurse@hospital.com",
    name: "Emily Rodriguez",
    role: "nurse",
    avatar: "/female-nurse.png",
    department: "Emergency",
    phone: "+1 (555) 345-6789",
    shift: "Day",
    isActive: true,
    lastLogin: new Date("2024-01-15T07:00:00Z"),
  },
  {
    id: "4",
    email: "receptionist@hospital.com",
    name: "Lisa Thompson",
    role: "receptionist",
    avatar: "/friendly-receptionist.png",
    department: "Front Desk",
    phone: "+1 (555) 456-7890",
    isActive: true,
    lastLogin: new Date("2024-01-15T08:00:00Z"),
  },
  {
    id: "5",
    email: "pharmacist@hospital.com",
    name: "David Kim",
    role: "pharmacist",
    avatar: "/pharmacist-consultation.png",
    department: "Pharmacy",
    phone: "+1 (555) 567-8901",
    licenseNumber: "RPH67890",
    isActive: true,
    lastLogin: new Date("2024-01-15T08:15:00Z"),
  },
  {
    id: "6",
    email: "patient@hospital.com",
    name: "John Smith",
    role: "patient",
    avatar: "/patient-consultation.png",
    phone: "+1 (555) 678-9012",
    dateOfBirth: new Date("1985-06-15"),
    address: "123 Main St, City, State 12345",
    emergencyContact: {
      name: "Jane Smith",
      relationship: "Spouse",
      phone: "+1 (555) 789-0123",
    },
    isActive: true,
    lastLogin: new Date("2024-01-14T16:30:00Z"),
  },
]

// Mock Patients Data
export const mockPatients: Patient[] = [
  {
    id: "P001",
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: new Date("1985-06-15"),
    gender: "Male",
    phone: "+1 (555) 678-9012",
    email: "john.smith@email.com",
    address: "123 Main St, City, State 12345",
    emergencyContact: {
      name: "Jane Smith",
      relationship: "Spouse",
      phone: "+1 (555) 789-0123",
    },
    insurance: {
      provider: "Blue Cross Blue Shield",
      policyNumber: "BC123456789",
      groupNumber: "GRP001",
    },
    medicalHistory: [
      {
        id: "MH001",
        condition: "Hypertension",
        diagnosedDate: new Date("2020-03-15"),
        status: "Active",
        notes: "Well controlled with medication",
      },
      {
        id: "MH002",
        condition: "Type 2 Diabetes",
        diagnosedDate: new Date("2019-08-22"),
        status: "Active",
        notes: "Managed with diet and medication",
      },
    ],
    medications: [
      {
        id: "MED001",
        name: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        prescribedDate: new Date("2020-03-15"),
        prescribedBy: "Dr. Michael Chen",
      },
      {
        id: "MED002",
        name: "Metformin",
        dosage: "500mg",
        frequency: "Twice daily",
        prescribedDate: new Date("2019-08-22"),
        prescribedBy: "Dr. Michael Chen",
      },
    ],
    vitalSigns: [
      {
        id: "VS001",
        date: new Date("2024-01-15"),
        bloodPressure: "128/82",
        heartRate: 72,
        temperature: 98.6,
        weight: 180,
        height: 70,
        recordedBy: "Emily Rodriguez",
      },
    ],
    allergies: ["Penicillin", "Shellfish"],
    bloodType: "A+",
    createdAt: new Date("2019-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "P002",
    firstName: "Maria",
    lastName: "Garcia",
    dateOfBirth: new Date("1992-11-08"),
    gender: "Female",
    phone: "+1 (555) 789-0123",
    email: "maria.garcia@email.com",
    address: "456 Oak Ave, City, State 12345",
    emergencyContact: {
      name: "Carlos Garcia",
      relationship: "Husband",
      phone: "+1 (555) 890-1234",
    },
    insurance: {
      provider: "Aetna",
      policyNumber: "AET987654321",
      groupNumber: "GRP002",
    },
    medicalHistory: [
      {
        id: "MH003",
        condition: "Asthma",
        diagnosedDate: new Date("2010-05-12"),
        status: "Active",
        notes: "Exercise-induced asthma, well controlled",
      },
    ],
    medications: [
      {
        id: "MED003",
        name: "Albuterol Inhaler",
        dosage: "90mcg",
        frequency: "As needed",
        prescribedDate: new Date("2023-06-15"),
        prescribedBy: "Dr. Sarah Johnson",
      },
    ],
    vitalSigns: [
      {
        id: "VS002",
        date: new Date("2024-01-14"),
        bloodPressure: "118/75",
        heartRate: 68,
        temperature: 98.4,
        weight: 135,
        height: 65,
        recordedBy: "Emily Rodriguez",
      },
    ],
    allergies: ["Latex"],
    bloodType: "O-",
    createdAt: new Date("2020-03-10"),
    updatedAt: new Date("2024-01-14"),
  },
]

// Mock Appointments Data
export const mockAppointments: Appointment[] = [
  {
    id: "APT001",
    patientId: "P001",
    patientName: "John Smith",
    doctorId: "2",
    doctorName: "Dr. Michael Chen",
    date: new Date("2024-01-16T10:00:00Z"),
    duration: 30,
    type: "Follow-up",
    status: "scheduled",
    reason: "Hypertension follow-up",
    notes: "Check blood pressure and medication effectiveness",
    priority: "medium",
    department: "Cardiology",
    createdAt: new Date("2024-01-10T14:30:00Z"),
    updatedAt: new Date("2024-01-10T14:30:00Z"),
  },
  {
    id: "APT002",
    patientId: "P002",
    patientName: "Maria Garcia",
    doctorId: "2",
    doctorName: "Dr. Michael Chen",
    date: new Date("2024-01-16T14:30:00Z"),
    duration: 45,
    type: "Consultation",
    status: "scheduled",
    reason: "Chest pain evaluation",
    notes: "Patient reports intermittent chest discomfort",
    priority: "high",
    department: "Cardiology",
    createdAt: new Date("2024-01-12T09:15:00Z"),
    updatedAt: new Date("2024-01-12T09:15:00Z"),
  },
  {
    id: "APT003",
    patientId: "P001",
    patientName: "John Smith",
    doctorId: "2",
    doctorName: "Dr. Michael Chen",
    date: new Date("2024-01-15T09:00:00Z"),
    duration: 30,
    type: "Follow-up",
    status: "completed",
    reason: "Diabetes check-up",
    notes: "Blood sugar levels stable, continue current medication",
    priority: "medium",
    department: "Cardiology",
    createdAt: new Date("2024-01-08T11:20:00Z"),
    updatedAt: new Date("2024-01-15T09:30:00Z"),
  },
]

// Mock Medications Data
export const mockMedications: Medication[] = [
  {
    id: "MED001",
    name: "Lisinopril",
    genericName: "Lisinopril",
    brandName: "Prinivil",
    category: "ACE Inhibitor",
    description: "Used to treat high blood pressure and heart failure",
    dosageForm: "Tablet",
    strength: "10mg",
    manufacturer: "Merck",
    ndc: "0006-0207-31",
    rxcui: "29046",
    dea: null,
    isControlled: false,
    sideEffects: ["Dizziness", "Headache", "Fatigue", "Dry cough"],
    contraindications: ["Pregnancy", "Angioedema history"],
    interactions: ["Potassium supplements", "NSAIDs"],
    createdAt: new Date("2020-01-01"),
    updatedAt: new Date("2023-06-15"),
  },
  {
    id: "MED002",
    name: "Metformin",
    genericName: "Metformin HCl",
    brandName: "Glucophage",
    category: "Antidiabetic",
    description: "Used to treat type 2 diabetes",
    dosageForm: "Tablet",
    strength: "500mg",
    manufacturer: "Bristol-Myers Squibb",
    ndc: "0087-6060-30",
    rxcui: "6809",
    dea: null,
    isControlled: false,
    sideEffects: ["Nausea", "Diarrhea", "Metallic taste"],
    contraindications: ["Kidney disease", "Liver disease"],
    interactions: ["Alcohol", "Contrast dye"],
    createdAt: new Date("2020-01-01"),
    updatedAt: new Date("2023-06-15"),
  },
]

// Mock Prescriptions Data
export const mockPrescriptions: Prescription[] = [
  {
    id: "RX001",
    patientId: "P001",
    patientName: "John Smith",
    doctorId: "2",
    doctorName: "Dr. Michael Chen",
    medicationId: "MED001",
    medicationName: "Lisinopril",
    dosage: "10mg",
    quantity: 30,
    refills: 5,
    instructions: "Take once daily in the morning",
    prescribedDate: new Date("2024-01-15T10:30:00Z"),
    status: "ready",
    priority: "routine",
    notes: "Continue current therapy",
    pharmacistId: "5",
    pharmacistName: "David Kim",
    filledDate: new Date("2024-01-15T15:45:00Z"),
    createdAt: new Date("2024-01-15T10:30:00Z"),
    updatedAt: new Date("2024-01-15T15:45:00Z"),
  },
  {
    id: "RX002",
    patientId: "P002",
    patientName: "Maria Garcia",
    doctorId: "2",
    doctorName: "Dr. Michael Chen",
    medicationId: "MED003",
    medicationName: "Albuterol Inhaler",
    dosage: "90mcg",
    quantity: 1,
    refills: 3,
    instructions: "Use as needed for shortness of breath",
    prescribedDate: new Date("2024-01-16T11:15:00Z"),
    status: "pending",
    priority: "urgent",
    notes: "Patient needs inhaler for exercise-induced asthma",
    createdAt: new Date("2024-01-16T11:15:00Z"),
    updatedAt: new Date("2024-01-16T11:15:00Z"),
  },
]

// Mock Inventory Data
export const mockInventory: InventoryItem[] = [
  {
    id: "INV001",
    medicationId: "MED001",
    medicationName: "Lisinopril 10mg",
    currentStock: 250,
    minStock: 50,
    maxStock: 500,
    unitCost: 0.25,
    supplier: "Cardinal Health",
    lotNumber: "LOT123456",
    expiryDate: new Date("2025-06-30"),
    location: "A-1-001",
    lastRestocked: new Date("2024-01-10"),
    status: "in-stock",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "INV002",
    medicationId: "MED002",
    medicationName: "Metformin 500mg",
    currentStock: 15,
    minStock: 25,
    maxStock: 300,
    unitCost: 0.15,
    supplier: "McKesson",
    lotNumber: "LOT789012",
    expiryDate: new Date("2024-12-31"),
    location: "A-2-003",
    lastRestocked: new Date("2023-12-15"),
    status: "low-stock",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-12-15"),
  },
  {
    id: "INV003",
    medicationId: "MED003",
    medicationName: "Albuterol Inhaler 90mcg",
    currentStock: 8,
    minStock: 10,
    maxStock: 50,
    unitCost: 25.5,
    supplier: "AmerisourceBergen",
    lotNumber: "LOT345678",
    expiryDate: new Date("2024-03-15"),
    location: "B-1-005",
    lastRestocked: new Date("2023-11-20"),
    status: "expiring-soon",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-11-20"),
  },
]

// Mock Dashboard Statistics
export const mockDashboardStats = {
  admin: {
    totalPatients: 1247,
    totalStaff: 156,
    todayAppointments: 48,
    revenue: 125000,
    occupancyRate: 78,
    patientSatisfaction: 4.6,
  },
  doctor: {
    todayAppointments: 12,
    pendingResults: 5,
    totalPatients: 234,
    avgConsultationTime: 28,
  },
  nurse: {
    assignedPatients: 8,
    pendingTasks: 6,
    completedTasks: 14,
    shift: "Day Shift",
  },
  receptionist: {
    todayAppointments: 48,
    waitingPatients: 3,
    checkedInToday: 35,
    pendingCheckouts: 2,
  },
  pharmacist: {
    pendingPrescriptions: 12,
    filledToday: 28,
    lowStockItems: 5,
    expiringItems: 3,
  },
  patient: {
    upcomingAppointments: 2,
    prescriptions: 3,
    lastVisit: new Date("2024-01-15"),
    nextAppointment: new Date("2024-01-22"),
  },
}
